version: '3.4'

services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis:alpine
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/catalog/Catalog.API/Dockerfile
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: services/basket/Basket.API/Dockerfile
  portainer:
    image: portainer/portainer-ce
volumes:
  mongo_data: 
  portainer_data:
